HealthNet/HealthNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('appointments.urls')),
    url(r'^', include('messaging.urls')),
    url(r'^', include('sysstats.urls')),
    url(r'^', include('testResults.urls')),
    url(r'^', include('prescriptions.urls')),
    url(r'^', include('transfer.urls')),
    url(r'^calendar/', include('calendarium.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthNet/calendarium/urls.py
"""URLs for the ``calendarium`` app."""
from django.conf.urls import url

from . import views


urlpatterns = [
    # event views
    url(r'^event/create/$',
        views.EventCreateView.as_view(),
        name='calendar_event_create'),

    url(r'^event/(?P<pk>\d+)/$',
        views.EventDetailView.as_view(),
        name='calendar_event_detail'),

    url(r'^event/(?P<pk>\d+)/update/$',
        views.EventUpdateView.as_view(),
        name='calendar_event_update'),

    url(r'^event/(?P<pk>\d+)/delete/$',
        views.EventDeleteView.as_view(),
        name='calendar_event_delete'),

    # occurrence views
    url(r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        views.OccurrenceDetailView.as_view(),
        name='calendar_occurrence_detail'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/update/$',  # NOPEP8
        views.OccurrenceUpdateView.as_view(),
        name='calendar_occurrence_update'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/delete/$',  # NOPEP8
        views.OccurrenceDeleteView.as_view(),
        name='calendar_occurrence_delete'),

    # calendar views
    url(r'^(?P<year>\d+)/(?P<month>\d+)/$',
        views.MonthView.as_view(),
        name='calendar_month'),

    url(r'^(?P<year>\d+)/week/(?P<week>\d+)/$',
        views.WeekView.as_view(),
        name='calendar_week'),

    url(r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        views.DayView.as_view(),
        name='calendar_day'),

    url(r'^get-events/$',
        views.UpcomingEventsAjaxView.as_view(),
        name='calendar_upcoming_events'),

    url(r'^$',
        views.CalendariumRedirectView.as_view(),
        name='calendar_current_month'),

]

HealthNet/core/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy

from . import views

urlpatterns = [
    url(r'^register/', views.register_patient_page, name='register'),
    url(r'^patient/', views.patient_landing, name='patient'),
    url(r'^patients/', views.view_patients, name='view patients'),
    url(r'^patientss/(?P<patient_id>\d+)/$', views.admitPatient, name='admit patients'),
    url(r'^update_self/', views.editownprofile, name='update'),
    # url(r'^update_user/', views.editownpatientprofile, name='update user'),
    url(r'^update_med_info/(?P<patient_id>[0-9]+)/',
        views.EditPatientMediInfo.as_view(success_url=reverse_lazy('view patients')), name='update medical info for'),
    url(r'^view_med_info/(?P<patient_id>[0-9]+)/',
        views.ViewPatientMediInfo.as_view(), name='view medical info for'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^export/', views.download, name='download'),
    url(r'^email/', views.email, name='email_info'),
    url(r'^landing/', views.landing, name='landing'),
    url(r'^nurse/', views.nurse_landing, name='nurse'),
    url(r'^doctor/', views.doctor_landing, name='doctor'),
    url(r'^hadmin/', views.admin_landing, name='admin'),
    url(r'^new_hospital/', views.NewHospital.as_view(), name='create new hospital'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^tests/', views.patient_tests, name='tests'),  # Not used any more, redirects to testResults
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^logs/', views.logs, name='logs'),
    url(r'^upload_patient/', views.upload_patient_info, name='upload patient'),
    url(r'^staffregister/', views.registerStaff, name='staffregister'),
    url(r'^adminregister/', views.register_admin_page, name='adminregister'),
    url(r'^doctorregister/', views.register_doctor_page, name='doctorregister'),
    url(r'^nurseregister/', views.register_nurse_page, name='nurseregister'),
    url(r'^$', views.main, name='main')

]

HealthNet/core/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.core.exceptions import ObjectDoesNotExist


class HospitalManager(models.Manager):
    """
    HospitalManager: manager for the hospital class.
    hospital - Hospital object
    """
    def create_hospital(self, name):
        hospital = self.create(name=name)
        return hospital


class Hospital(models.Model):
    """
    Hospital: location that all user types have. Can be edited by Doctors/Admins.
    name - string for hospital's name
    """
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Nurse(models.Model):
    """
    Nurse: employee user class that can edit specific information and admit Patients.
    user - the User object that is extended
    hospital - the hospital object that the nurse is located at
    phoneNum - string with nurse's phone contact ('xxx-xxx-xxxx')
    """
    user = models.OneToOneField(User)
    hospital = models.ForeignKey(Hospital)
    phoneNum = models.CharField(max_length=11)

    def __str__(self):
        return self.user.get_full_name()

    @classmethod
    def create(cls, user, hospital_string, phoneNum_string):
        user.groups.add(Group.objects.get(name='Nurse'))
        return cls(user=user, hospital=Hospital.objects.get(name=hospital_string), phoneNum=phoneNum_string)


class Doctor(models.Model):
    """
    Doctor: employee user class that can edit Patient info, set up Appointments, release test information,
            and admit Patients.
    user - the User object that is extended
    phoneNum - string with doctor's phone contact ('xxx-xxx-xxxx')
    """
    user = models.OneToOneField(User)
    hospital = models.ForeignKey(Hospital)
    phoneNum = models.CharField(max_length=11)

    def __str__(self):
        return self.user.get_full_name()

    @classmethod
    def create(cls, user, hospital_string, phoneNum_string):
        user.groups.add(Group.objects.get(name='Doctor'))
        return cls(user=user, hospital=Hospital.objects.get(name=hospital_string), phoneNum=phoneNum_string)


class Admin(models.Model):
    """
    Admin: employee user class that can access logs
    user - the User object that is extended

    """
    user = models.OneToOneField(User)

    def __str__(self):
        return self.user.get_full_name()

    @classmethod
    def create(cls, user):
        user.groups.add(Group.objects.get(name='Admin'))
        return cls(user=user)


class Patient(models.Model):
    """
    Patient: One to one relationship with the User model in order to manage all patients as individual users. Contains
    info pertinent to Doctors and Nurses, such as Blood type and height/weight.
    
    user - links to associated User
    
    birthday - date used to determine age
    
    sex - biological sex, since doctors are concerned with anatomy and hormone balance. 3rd option is provided in
    ambiguous cases.
    
    blood type - simple, on of the 8 possible blood types or unknown
    
    height - currently an integer as one's height in inches
    
    weight - one's weight in pounds
    
    allergies - for now this is a simple text field, but soon this will be a comma separated list of one's allergies
    that will be made browsable (R2) by the Doctor
    
    insurance info - simple character field meant to store one's insurance ID.
    
    preferred hospital - used when a patient has a choice of hospital
    
    hospital - Hospital that the Patient is currently in
    
    emergency contact - self explanatory, can also be linked to another user in the hospital
    
    emergency contact user - links to user (if one exists) in the system that matches the email in the field above
    
    admitted - true if currently admitted, false otherwise
    """
    user = models.OneToOneField(User)
    birthday = models.DateField(default="1800-01-01")
    SEX_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
        ("N", "Neither"),
    )
    sex = models.CharField(max_length=5, choices=SEX_CHOICE, default="M")
    BLOOD_TYPE = (
        ("A+", "A+"),
        ("B+", "B"),
        ("O+", "O+"),
        ("AB+", "AB+"),
        ("A-", "A-"),
        ("B-", "B-"),
        ("O-", "O-"),
        ("AB-", "AB-"),
        ("UN", "Unknown"),
    )
    blood_type = models.CharField(max_length=10, choices=BLOOD_TYPE, default="UN")
    height = models.CharField(max_length=7, null=True)
    weight = models.PositiveSmallIntegerField(null=True)
    allergies = models.TextField(max_length=1000, default="")
    medical_history = models.TextField(max_length=1000, default="")

    insurance_info = models.CharField(max_length=50)
    preferred_hospital = models.ForeignKey(Hospital, null=True, related_name="preferred_hospital")
    hospital = models.ForeignKey(Hospital, null=False, related_name="current_hospital")
    emergency_contact = models.EmailField()
    emergency_contact_user = models.ForeignKey(User, null=True, related_name='emergency_user')

    admitted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.get_full_name()

    @classmethod
    def create(cls, user, birthday_string, sex_verbose, b_type, height, weight, allergies, med_hist, insurance,
               p_hos_string, emerg_con_email):
        try:
            emerg_con_user = User.objects.get(email=emerg_con_email)
        except ObjectDoesNotExist:
            emerg_con_user = None

        user.groups.add(Group.objects.get(name='Patient'))

        return cls(user=user, birthday=birthday_string, sex=sex_verbose,
                   blood_type=b_type, height=height, weight=weight, allergies=allergies, medical_history=med_hist,
                   insurance_info=insurance, preferred_hospital=Hospital.objects.get(name=p_hos_string),
                   hospital=Hospital.objects.get(name=p_hos_string), emergency_contact=emerg_con_email,
                   emergency_contact_user=emerg_con_user, admitted=True)


class LogManager(models.Manager):
    """
    LogManager: Manages Logs
    log - Log created to be stored
    """
    def create_Log(self, user, username, time, log_type):
        log = self.create(user=user, username=username, time=time, type=log_type)
        return log


class Log(models.Model):
    """
    Log: contains a single log entry.
    user - the USer who generated this entry
    username - self explanatory
    time - the time this action was logged
    type - what action was performed
    """
    user = models.ForeignKey(User, verbose_name='User')
    username = models.CharField(default='', max_length=100, verbose_name='Username')

    time = models.DateTimeField(verbose_name='Date Logged')
    type = models.CharField(max_length=100, verbose_name='Type')

    objects = LogManager()

    def __str__(self):
        return self.type

HealthNet/core/forms.py
from django.utils import timezone

from django import forms
from django.contrib.auth.models import User

from datetimewidget.widgets import DateWidget
from .models import Patient, Hospital, Doctor, Nurse


class UserRegForm(forms.ModelForm):
    """
    Form for user registration
    """
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(UserRegForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})

    def is_valid(self):
        return super(UserRegForm, self).is_valid() and \
               User.objects.all().filter(email=self.cleaned_data['email']).count() == 0


class UserUpdateForm(forms.ModelForm):
    """
    Form for user updates
    """

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']


class PatientRegForm(forms.ModelForm):
    """
    Form for patient registration
    Note: Seperate from user registration form
    """
    now = timezone.now()
    birthday = forms.DateField(widget=DateWidget(usel10n=True, bootstrap_version=3))
    preferred_hospital = forms.ModelChoiceField(queryset=Hospital.objects.all(), required=False)
    # hospital = forms.ModelChoiceField(queryset=Hospital.objects.all(), required=True)
    emergency_contact = forms.EmailField(label="Emergency Contact Email Address:")

    class Meta:
        model = Patient
        fields = ('birthday', 'sex', 'blood_type', 'height', 'weight', 'allergies', 'medical_history', 'insurance_info',
                  'emergency_contact', 'preferred_hospital')  # , 'hospital')

    def __init__(self, *args, **kwargs):
        super(PatientRegForm, self).__init__(*args, **kwargs)

        self.fields['birthday'].widget.attrs.update({'class': 'form-control'})
        self.fields['sex'].widget.attrs.update({'class': 'form-control'})
        self.fields['blood_type'].widget.attrs.update({'class': 'form-control'})
        self.fields['height'].widget.attrs.update({'class': 'form-control'})
        self.fields['weight'].widget.attrs.update({'class': 'form-control'})
        self.fields['allergies'].widget.attrs.update({'class': 'form-control'})
        self.fields['insurance_info'].widget.attrs.update({'class': 'form-control'})
        self.fields['emergency_contact'].widget.attrs.update({'class': 'form-control'})
        self.fields['preferred_hospital'].widget.attrs.update({'class': 'form-control'})
        self.fields['medical_history'].widget.attrs.update({'class': 'form-control'})
        # self.fields['hospital'].widget.attrs.update({'class': 'form-control'})


class NurseRegForm(forms.ModelForm):
    """
    Form for Nurse registration
    Note: Seperate from user registration form
    """
    now = timezone.now()
    phoneNum = forms.IntegerField(label="Phone Number")
    hospital = forms.ModelChoiceField(queryset=Hospital.objects.all(), required=True, label="Hospital")

    class Meta:
        model = Nurse
        fields = ('phoneNum', 'hospital')


class DoctorRegForm(forms.ModelForm):
    """
    Form for Doctor registration
    Note: Seperate from user registration form
    """
    phoneNum = forms.IntegerField(label="Phone Number")
    hospital = forms.ModelChoiceField(queryset=Hospital.objects.all(), required=True, label="Hospital")

    class Meta:
        model = Doctor
        fields = ('phoneNum', 'hospital')


class LoginForm(forms.ModelForm):
    """
    Form for logging in
    """

    class Meta:
        model = User
        username = forms.CharField(max_length=50)
        password = forms.CharField(max_length=50)
        fields = ["username", "password"]


class PatientForm(forms.ModelForm):
    """
    Form for accessing Patient Data
    """

    class Meta:
        model = Patient
        fields = ['birthday', 'sex', 'height', 'weight', 'allergies', 'medical_history', 'insurance_info',
                  'emergency_contact', 'preferred_hospital']


class PatientMediForm(forms.ModelForm):
    """
    Form for accessing Patient Medical Data
    """

    class Meta:
        model = Patient
        fields = ('sex', 'blood_type', 'height', 'weight', 'allergies', 'medical_history')


class UploadFileForm(forms.Form):
    """
    Form for Uploading Files
    """
    file = forms.FileField()


class NewHospitalForm(forms.ModelForm):
    """
    Form for creating a new Hospital
    """
    class Meta:
        model = Hospital
        fields = ('name',)

HealthNet/core/templates/core/landing/pages/edit_profile.html
{% extends "core/landing/Patient.html" %}

{% block title %}Edit Profile{% endblock %}

{% block pageContents %}
    <div class="row text-center">
        <div class="col-md-1">
        </div>
        <div class="col-md-10">
            <form enctype="multipart/form-data" action="" method="post">{% csrf_token %}
                {{ user_form.as_p }}
                {{ patient_form.as_p }}
                <input type="submit" value="Save" />
            </form>
        </div>
        <div class="col-md-1">
        </div>
    </div>
{% endblock %}

HealthNet/core/templates/core/landing/pages/email_success.html
{% extends 'core/landing/Patient.html' %}
{% load userGroup %}

{% block title %}Success!{% endblock %}

{% block pageContents %}

    <h1>Success!</h1>
    <p>Email sent to {{ request.user.email }}</p>

    <script>
        window.setTimeout(function(){
            window.location.href = {% url 'landing' %};
        }, 10000);
    </script>

{% endblock pageContents %}

HealthNet/core/templates/core/landing/pages/profile.html
{% extends parent %}
{% load userGroup %}


{% block title %}Patient Profile{% endblock %}

{% block pageContents %}

<div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-10">
            <h4>
               User : {{ request.user.get_full_name}}
            </h4>

            <h4>
                Email : {{ request.user.email }}
            </h4>

            {% if request.user|in_group:"Patient" %}

                <h4>
                    Birthday : {{ request.user.patient.birthday }}
                </h4>
                <h4>
                    Gender : {{ request.user.patient.get_sex_display }}
                </h4>
                <h4>
                    Blood Type : {{ request.user.patient.get_blood_type_display }}
                </h4>
                <h4>
                    Height : {{ request.user.patient.height }}
                </h4>
                <h4>
                    Weight : {{ request.user.patient.weight }}
                </h4>
                <h4>
                    Allergies : {{ request.user.patient.allergies }}
                </h4>
                <h4>
                    Medical History : {{ request.user.patient.medical_history }}
                </h4>
                <h4>
                    Insurance Info : {{ request.user.patient.insurance_info }}
                </h4>
                <h4>
                    Emergency Contact : {{ request.user.patient.emergency_contact }}
                </h4>
                <h4>
                    Preferred Hospital : {{ request.user.patient.preferred_hospital }}
                </h4>
                <h4>
                    Hospital : {{ request.user.patient.hospital }}
                </h4>

                <div class="text-center">
                    <a href="{% url 'update' %}" class="btn btn-info" role="button">Edit Profile</a>
                    <a href="javascript:privacywarning();" class="btn btn-info" role="button">Email myself this info</a>
                    <a href="{% url 'download' %}" class="btn btn-info" role="button">Download this info</a>
                </div>
            {% elif request.user|in_group:"Nurse" %}

                <h4>
                    Hospital : {{ request.user.nurse.hospital }}
                </h4>
                <h4>
                    Phone Number : {{ request.user.nurse.phoneNum }}
                </h4>

                <div class="text-center">
                    <a href="{% url 'update' %}" class="btn btn-info" role="button">Edit Profile</a>
                </div>
            {% elif request.user|in_group:"Doctor" %}
                <h4>
                    Phone Number : {{ request.user.doctor.phoneNum }}
                </h4>
                <h4>
                    Hospital : {{ request.user.doctor.hospital }}
                </h4>

                <div class="text-center">
                    <a href="{% url 'update' %}" class="btn btn-info" role="button">Edit Profile</a>
                </div>

            {% elif request.user|in_group:"Admin" %}

                <div class="text-center">
                    <a href="{% url 'update' %}" class="btn btn-info" role="button">Edit Profile</a>
                </div>

            {% else %}

                <h2 style="color: #921e12">
                    No User found. <!--Added by Jim on 4/4/17 for testing-->
                </h2>

            {% endif %}

        </div>
        <div class="col-md-1">
        </div>
    </div>

    <script type="text/javascript">
        function privacywarning() {
            var answer = confirm ("This sends your Medical Information to you in plain text. If someone else intercepts"
                + " this, they could view your sensitive information. Proceed?");
            if (answer)
                window.location="{% url 'email_info' %}";
            }
    </script>

{% endblock %}

HealthNet/core/templates/core/landing/pages/registration_select.html
{% extends "core/landing/baselanding.html" %}

{% block title %}Registration Selection{% endblock %}

{% block pageContents %}
    <div class="row text-center">
        <div class="col-md-4">
            <a href="{% url 'nurseregister'  %}" class="btn btn-info" role="button">Create a Nurse</a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'doctorregister'  %}" class="btn btn-info" role="button">Create a Doctor</a>
        </div>
        <div class="col-md-4">
            <a href="{% url 'adminregister'  %}" class="btn btn-info" role="button">Create an Admin</a>
        </div>
    </div>
{% endblock %}