HealthNet/HealthNet/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('appointments.urls')),
    url(r'^', include('messaging.urls')),
    url(r'^', include('sysstats.urls')),
    url(r'^', include('testResults.urls')),
    url(r'^', include('prescriptions.urls')),
    url(r'^', include('transfer.urls')),
    url(r'^calendar/', include('calendarium.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

HealthNet/calendarium/urls.py
"""URLs for the ``calendarium`` app."""
from django.conf.urls import url

from . import views


urlpatterns = [
    # event views
    url(r'^event/create/$',
        views.EventCreateView.as_view(),
        name='calendar_event_create'),

    url(r'^event/(?P<pk>\d+)/$',
        views.EventDetailView.as_view(),
        name='calendar_event_detail'),

    url(r'^event/(?P<pk>\d+)/update/$',
        views.EventUpdateView.as_view(),
        name='calendar_event_update'),

    url(r'^event/(?P<pk>\d+)/delete/$',
        views.EventDeleteView.as_view(),
        name='calendar_event_delete'),

    # occurrence views
    url(r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        views.OccurrenceDetailView.as_view(),
        name='calendar_occurrence_detail'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/update/$',  # NOPEP8
        views.OccurrenceUpdateView.as_view(),
        name='calendar_occurrence_update'),

    url(
        r'^event/(?P<pk>\d+)/date/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/delete/$',  # NOPEP8
        views.OccurrenceDeleteView.as_view(),
        name='calendar_occurrence_delete'),

    # calendar views
    url(r'^(?P<year>\d+)/(?P<month>\d+)/$',
        views.MonthView.as_view(),
        name='calendar_month'),

    url(r'^(?P<year>\d+)/week/(?P<week>\d+)/$',
        views.WeekView.as_view(),
        name='calendar_week'),

    url(r'^(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        views.DayView.as_view(),
        name='calendar_day'),

    url(r'^get-events/$',
        views.UpcomingEventsAjaxView.as_view(),
        name='calendar_upcoming_events'),

    url(r'^$',
        views.CalendariumRedirectView.as_view(),
        name='calendar_current_month'),

]

HealthNet/core/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy

from . import views

urlpatterns = [
    url(r'^register/', views.register_patient_page, name='register'),
    url(r'^patient/', views.patient_landing, name='patient'),
    url(r'^patients/', views.view_patients, name='view patients'),
    url(r'^patientss/(?P<patient_id>\d+)/$', views.admitPatient, name='admit patients'),
    url(r'^update_self/', views.editownprofile, name='update'),
    # url(r'^update_user/', views.editownpatientprofile, name='update user'),
    url(r'^update_med_info/(?P<patient_id>[0-9]+)/',
        views.EditPatientMediInfo.as_view(success_url=reverse_lazy('view patients')), name='update medical info for'),
    url(r'^view_med_info/(?P<patient_id>[0-9]+)/',
        views.ViewPatientMediInfo.as_view(), name='view medical info for'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^export/', views.download, name='download'),
    url(r'^email/', views.email, name='email_info'),
    url(r'^landing/', views.landing, name='landing'),
    url(r'^nurse/', views.nurse_landing, name='nurse'),
    url(r'^doctor/', views.doctor_landing, name='doctor'),
    url(r'^hadmin/', views.admin_landing, name='admin'),
    url(r'^new_hospital/', views.NewHospital.as_view(), name='create new hospital'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^tests/', views.patient_tests, name='tests'),  # Not used any more, redirects to testResults
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^logs/', views.logs, name='logs'),
    url(r'^upload_patient/', views.upload_patient_info, name='upload patient'),
    url(r'^staffregister/', views.registerStaff, name='staffregister'),
    url(r'^adminregister/', views.register_admin_page, name='adminregister'),
    url(r'^doctorregister/', views.register_doctor_page, name='doctorregister'),
    url(r'^nurseregister/', views.register_nurse_page, name='nurseregister'),
    url(r'^$', views.main, name='main')

]

HealthNet/calendarium/forms.py
"""Forms for the ``calendarium`` app."""
from django import forms
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from django.utils.timezone import datetime, timedelta

from .constants import OCCURRENCE_DECISION_CHOICESS, OCCURRENCE_DECISIONS
from .models import Event, Occurrence


class OccurrenceForm(forms.ModelForm):
    """A form for the ``Occurrence`` model."""
    decision = forms.CharField(
        widget=forms.Select(choices=OCCURRENCE_DECISION_CHOICESS),
    )

    cancelled = forms.BooleanField(
        widget=forms.HiddenInput,
        required=False,
    )

    original_start = forms.DateTimeField(
        widget=forms.HiddenInput,
    )

    original_end = forms.DateTimeField(
        widget=forms.HiddenInput,
    )

    event = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Event.objects.all(),
    )

    class Meta:
        model = Occurrence
        exclude = []

    def save(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['decision'] == OCCURRENCE_DECISIONS['all']:
            changes = dict(
                (key, value) for key, value in iter(cleaned_data.items())
                if value != self.initial.get(key) and self.initial.get(key))
            event = self.instance.event
            # for each field on the event, check for new data in cleaned_data
            for field_name in [field.name for field in event._meta.fields]:
                value = changes.get(field_name)
                if value:
                    setattr(event, field_name, value)
            event.save()

            # repeat for persistent occurrences
            for occ in event.occurrences.all():
                for field_name in [field.name for field in occ._meta.fields]:
                    value = changes.get(field_name)
                    if value:
                        # since we can't just set a new datetime, we have to
                        # adjust the datetime fields according to the changes
                        # on the occurrence form instance
                        if type(value) != datetime:
                            setattr(occ, field_name, value)
                        else:
                            initial_time = self.initial.get(field_name)
                            occ_time = getattr(occ, field_name)
                            delta = value - initial_time
                            new_time = occ_time + delta
                            setattr(occ, field_name, new_time)
                occ.save()

            # get everything from initial and compare to cleaned_data to
            # retrieve what has been changed
            # apply those changes to the persistent occurrences (and the main
            # event)
        elif cleaned_data['decision'] == OCCURRENCE_DECISIONS['this one']:
            self.instance.save()
        elif cleaned_data['decision'] == OCCURRENCE_DECISIONS['following']:
            # get the changes
            changes = dict(
                (key, value) for key, value in iter(cleaned_data.items())
                if value != self.initial.get(key) and self.initial.get(key))

            # change the old event
            old_event = self.instance.event
            end_recurring_period = self.instance.event.end_recurring_period
            old_event.end_recurring_period = self.instance.start - timedelta(
                days=1)
            old_event.save()

            # the instance occurrence holds the info for the new event, that we
            # use to update the old event's fields
            new_event = old_event
            new_event.end_recurring_period = end_recurring_period
            new_event.id = None
            event_kwargs = model_to_dict(self.instance)
            for field_name in [field.name for field in new_event._meta.fields]:
                if (field_name == 'created_by' and
                        event_kwargs.get('created_by')):
                    value = User.objects.get(pk=event_kwargs.get(field_name))
                elif field_name in ['rule', 'category']:
                    continue
                else:
                    value = event_kwargs.get(field_name)
                if value:
                    setattr(new_event, field_name, value)
            new_event.save()

HealthNet/calendarium/templates/calendarium/calendar_day.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Occurrences" %}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" name="previous" value="{% trans "Previous" %}" />
    <input type="submit" name="next" value="{% trans "Next" %}" />
    <input type="submit" name="today" value="{% trans "Today" %}" />
</form>
<table class="table">
    <tr>
        <th>{{ date|date:'D m/d' }}</th>
    </tr>
    <tr>
        {% for occurrence in occurrences %}
            <td><p>{{ occurrence }}</p></td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

HealthNet/calendarium/templates/calendarium/calendar_month.html
{% extends "base.html" %}
{% load i18n calendarium_tags %}
{% load userGroup %}



{% block main %}
<h1>{{ date|date:"F Y" }}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <input class="btn btn-default" type="submit" name="previous" value="{% trans "Previous" %}" />
    <input class="btn btn-default" type="submit" name="next" value="{% trans "Next" %}" />
    <input class="btn btn-default" type="submit" name="today" value="{% trans "Today" %}" />

    {% if request.user|in_group:"Patient" or request.user|in_group:"Doctor" or request.user|in_group:"Nurse" %}
    <a href="{% url "calendar_event_create" %}" class="btn btn-info" role="button">{% trans "Create Appointment"%}</a>
        <!--<a href="{# url "calendar_event_create" #}">{# trans "Create Appointment" #}</a>-->
    {% endif %}
</form>
<table class="table" id="calendar-month">
    <tr>
        <th></th>
        {% for weekday in weekdays %}
            <th>{{ weekday }}</th>
        {% endfor %}
    </tr>
    {% for week in month %}
        {% if week %}
            <tr>
                <td class="calendarium-week-link"><a href="{{ date|get_week_URL:week.0.0 }}">{% trans "View" %}</a></td>
                {% for day, occurrences, current in week %}
                    <td class=" {% if day == 0 %}
                                    calendarium-empty
                                {% elif current %}
                                    calendarium-current
                                {% else %}
                                    calendarium-day
                                {% endif %}">
                        <div class="calendarium-relative">
                            {% if day != 0 %}
                                <span class="calendarium-date">{{ day }}</span>
                                {% for occurrence in occurrences %}
                                    <!--<p class="alert" style="background-color: #{# occurrence.event.category.color #}">-->
                                        <!--<a title="{# occurrence #}" style="font-size:100%;"
                                        href="{# url "calendar_occurrence_detail" pk=occurrence.event.pk
                                                      year=occurrence.start.year month=occurrence.start.month
                                                      day=occurrence.start.day #}">{# occurrence|truncatechars:22 #}
                                        </a>-->
                                    <!--</p>-->
                                    <p style="border:3px; border-style:solid; border-color:#{{ occurrence.event.category.color }}; padding: 3px; text-align:center;">
                                        <a title="{{ occurrence }}"  style="font-size:100%;"
                                           href="{% url "calendar_occurrence_detail" pk=occurrence.event.pk year=occurrence.start.year month=occurrence.start.month day=occurrence.start.day %}">
                                            {{ occurrence|truncatechars:22 }}</a>
                                    </p>

                                {% endfor %}
                            {% endif %}
                        </div>
                    </td>
                {% endfor %}
            </tr>
        {% endif %}
    {% endfor %}
</table>
{% render_upcoming_events 5 current_category %}
{% endblock %}

HealthNet/calendarium/templates/calendarium/calendar_week.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{{ date|date:"F Y" }}{% trans " Week View" %}</h1>
{% include "calendarium/partials/category_list.html" %}
<form action="." method="post">
    {% csrf_token %}
    <input type="submit" name="previous" value="{% trans "Previous" %}" />
    <input type="submit" name="next" value="{% trans "Next" %}" />
    <input type="submit" name="today" value="{% trans "Today" %}" />
</form>
<table class="table" id="calendar-week">
    <tr>
        {% for date, occurrences, current in week %}
            <th>{{ date|date:'D m/d' }}</th>
        {% endfor %}
    </tr>
    <tr>
        {% for date, occurrences, current in week %}
            <td class="{% if current %}calendarium-current{% endif %}">
                <div class="calendarium-relative">
                    {% for occurrence in occurrences %}
                        <p style="background-color: #{{ occurrence.event.category.color }}; text-align:center;">
                            <a title="{{ occurrence }}"  style="font-size:100%;"
                               href="{% url "calendar_occurrence_detail" pk=occurrence.event.pk year=occurrence.start.year month=occurrence.start.month day=occurrence.start.day %}">
                                {{ occurrence|truncatechars:22 }}</a>
                        </p>
                    {% endfor %}
                </div>
            </td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

HealthNet/calendarium/templates/calendarium/event_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Delete" %} {{ object }}</h1>
<form method="post" action=".">
    {% csrf_token %}
    {% trans "Do you really want to delete this event?" %}
    <input type="submit" value="{% trans "Delete" %}" />
</form>
{% endblock %}

HealthNet/calendarium/templates/calendarium/event_detail.html
{% extends "base.html" %}
{% load i18n %}

{% load userGroup %}

{% block main %}
<h1>{{ object }}</h1>
<table>
    <tr>
        <th>{% trans "Start" %}</th>
        <td>{{ object.start }}</td>
    </tr>
    <tr>
        <th>{% trans "End" %}</th>
        <td>{{ object.end }}</td>
    </tr>
    <tr>
        <th>{% trans "Doctor" %}</th>
        <td>{{ object.category }}</td>
    </tr>
    <tr>
        <th>{% trans "Patient" %}</th>
        <td>{{ object.created_by }}</td>
    </tr>
    <tr>
        <th>{% trans "Description" %}</th>
        <td>{{ object.description }}</td>
    </tr>

</table>
<a href="{% url "calendar_current_month" %}">{% trans "Back" %}</a>
    <a href="{% url "calendar_event_update" pk=object.pk %}">{% trans "Edit" %}</a>
{% if request.user|in_group:"Patient" or request.user|in_group:"Doctor" %}
    <a href="{% url "calendar_event_delete" pk=object.pk %}">{% trans "Delete" %}</a>
{% endif %}
{% endblock %}

HealthNet/calendarium/templates/calendarium/event_form.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>
    {% if form.instance.id %}
        {% trans "Update" %} {{ form.instance }}
    {% else %}
        {% trans "Create event" %}
    {% endif %}
</h1>
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Save" %}" />
</form>
{% if form.instance.id %}
    <a href="{% url "calendar_event_delete" pk=form.instance.pk %}">{% trans "Delete" %}</a>
{% endif %}
{% endblock %}

HealthNet/calendarium/templates/calendarium/occurrence_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
<h1>{% trans "Delete" %} {{ object }}</h1>
<form method="post" action="{% url "calendar_occurrence_delete" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">
    {% csrf_token %}
    <p>
        <label for="id_event">{% trans "Decision" %}:</label>
        <select name="decision">
            {% for decision in decisions %}
                <option value="{{ decision }}">{{ decision }}</option>
            {% endfor %}
        </select>
    </p>
    <a href="{% url "calendar_occurrence_update" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">{% trans "Back" %}</a>
    <input type="submit" value="{% trans "Delete" %}" />
</form>
{% endblock %}

HealthNet/calendarium/templates/calendarium/occurrence_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load userGroup %}

{% block main %}
<h1>{{ object }}</h1>
<table>
    <tr>
        <th>{% trans "Start" %}</th>
        <td>{{ object.start }}</td>
    </tr>
    <tr>
        <th>{% trans "End" %}</th>
        <td>{{ object.end }}</td>
    </tr>
    <tr>
        <th>{% trans "Patient " %}</th>
        <td>{{ object.created_by }}</td>
    </tr>
    <tr>
        <th>{% trans "Doctor" %}</th>
        <td>{{ object.category }}</td>
    </tr>
    <tr>
        <th>{% trans "Description " %}</th>
        <td>{{ object.description }}</td>
    </tr>
</table>
<a href="{% url "calendar_current_month" %}">{% trans "Back" %}</a>
<a href="{% url "calendar_occurrence_update" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">
    {% trans "Edit" %}</a>
{% if request.user|in_group:"Patient" or request.user|in_group:"Doctor"  %}
    <a href="{% url "calendar_occurrence_delete" pk=object.event.pk year=object.start.year month=object.start.month day=object.start.day %}">
        {% trans "Delete" %}</a>
{% endif %}
{% endblock %}

HealthNet/calendarium/templates/calendarium/occurrence_form.html
{% extends "base.html" %}
{% load i18n %}
{% load userGroup %}

{% block main %}
<h1>
    {% if form.instance.id %}
        {% trans "Update" %} {{ form.instance }}
    {% else %}
        {% trans "Create event" %}
    {% endif %}
</h1>
<form method="post" action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans "Save" %}" />
</form>
{% if request.user|in_group:"Patient" or request.user|in_group:"Doctor"  %}
    <a href="{% url "calendar_occurrence_delete" pk=form.instance.event.pk year=form.instance.start.year month=form.instance.start.month day=form.instance.start.day %}">{% trans "Delete" %}</a>
{% endif %}
{% endblock %}

HealthNet/calendarium/templates/calendarium/upcoming_events.html
<ul>
    {% for occurrence in occurrences %}
        <li>{{ occurrence.title }}</li>
    {% endfor %}
</ul>